### ISSUE TITLE
Teensy

### ISSUE THREAD

**Issue by bluepuppy** [teemuatlut/TMC2130Stepper#16]
I'm trying to get my new TMC2130 drivers to work with the Teensy 3.6.  I had the 2100 drivers working fine.  I have the EN, DIR, STEP and CS pins connected to digital pins on the Teensy and no joy.  The Simple example makes no reference to a SPI library, so I'm assuming I dont need to run those wires for this example?  Or are they needed regardless...

Teensy pinout is [here](https://www.pjrc.com/teensy/pinout.html)

Would love some fritzing diagrams of the wiring.. but from what I see, this looks to be a great library.. if I can get it work, it'd even better ;)

**Comment by teemuatlut** [comment]
You do need the wires. The SPI library is included by the TMC2130Stepper library so you don't need to include it yourself.

Better documentation is definitely required...
