### ISSUE TITLE
Live Tune example wont compile - Teensy 3.6

### ISSUE THREAD

**Issue by bluepuppy** [teemuatlut/TMC2130Stepper#17]
Trying to get my motor to work, loaded the live tune example and got this error...

`Arduino: 1.8.5 (Mac OS X), TD: 1.40, Board: "Teensy 3.6, Serial, 180 MHz, Faster, US English"

Live_tune:15: error: expected constructor, destructor, or type conversion before '(' token
 ISR(TIMER1_COMPA_vect){//timer1 interrupt 1Hz toggles pin 13 (LED)
     ^
Live_tune:15: error: expected constructor, destructor, or type conversion before '(' token
 ISR(TIMER1_COMPA_vect){//timer1 interrupt 1Hz toggles pin 13 (LED)
    ^
expected constructor, destructor, or type conversion before '(' token

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by teemuatlut** [comment]
That example uses direct register manipulation which is different for every platform. You will need to change the code to be Teensy or MK64FX512 compatible for it to work. The current code is for AVR.
