### ISSUE TITLE
Software SPI doesn't read data

### ISSUE THREAD

**Issue by q3ok** [teemuatlut/TMC2130Stepper#21]
While using SoftSPI, there is no possibility to read any data from the driver, arduino sets all the options properly. The drivers are working properly, as using standard arduino SPI it's working OK.
Board used: Arduino Mega 2560 (chinese clone), tested with different boards, different tmc2130, and different pins for MISO MOSI SCK.

**Comment by q3ok** [comment]
#22

**Comment by teemuatlut** [comment]
Addressed in v2.1.5.
