### ISSUE TITLE
Enable CoolStep - Digital current control

### ISSUE THREAD

**Issue by alfredanil** [teemuatlut/TMC2130Stepper#29]
Sensorless homing is amazing but it just does not stop here as it can also be used for sensorless load-dependent current control that uses StallGuard2 as well. Why not bring this remarkable feature to life?

**Comment by teemuatlut** [comment]
The Marlin v1.1.x branch is in a feature freeze so I'm not making any new features until v1.1.9 is released and focus starts to shift towards the v2 branch.
For now you can configure coolStep for yourself by using the TMC_ADV feature.

**Comment by alfredanil** [comment]
Could you give some tips on how to configure CoolStep feature.

**Comment by teemuatlut** [comment]
You can look for an example in the `StallGuard` example.
```
driver.THIGH(0);
driver.semin(5);
driver.semax(2);
driver.sedn(0b01);
```
Only the `semin` is necessary but the rest adjust the current slopes a bit.

**Comment by teemuatlut** [comment]
https://github.com/teemuatlut/Marlin/tree/bf2_coolstep
