### ISSUE TITLE
TMC2130 with Accelstepper Library

### ISSUE THREAD

**Issue by FlowBo** [teemuatlut/TMC2130Stepper#33]
I'm trying to run a Stepper with TMC2130 in combination with the AccelStepper Library.
The Stepper is making the correct sound (i can hear the acceleration and velocity etc) but the shaft is not turning.
If I step it manually with digitalWrite() HIGH - LOW it is moving.

**Comment by teemuatlut** [comment]
Try using some simple example from the AccelStepper library and add the TMC2130 configuration parameters into that.
As long as the driver has been configured and gets step pulses and enable is low the motor should move.

**Comment by teemuatlut** [comment]
The default is 0, which means 256 microsteps.

**Comment by danielawd** [comment]
@FlowBo 
I understand you got Accelstepper to work with 2130?
Would you share some code, i am about to try it...
Did you got it working in SPI mode and with multiple steppers?

Thanks
Daniel
