### ISSUE TITLE
TMC2130.stealthChop(1); not working straight away with version 2.0.0 (Simple example)

### ISSUE THREAD

**Issue by musinou** [teemuatlut/TMC2130Stepper#5]
After an update of the library, turning stealthChop on did not work out-of-the-box, as it worked on the Simple example on the version 1.1.0 of the library.

Had to adjust stealth_amplitude and stealth_gradient to make it work. 

It would be sweet to either change the Simple example or changing the default values.

**Comment by teemuatlut** [comment]
Thanks for letting me know. I'll take a look at it next week.

**Comment by musinou** [comment]
Thank you for your great work with this library!
