### ISSUE TITLE
Read TSTEP register, but the value is small

### ISSUE THREAD

**Issue by ziyangwang007** [teemuatlut/TMC2130Stepper#76]
Hi,

I just have a problem.

When I read the data from TSTEP registers, the value is quite small and it usually be 0. I tried to set the delay time between the "steppin" high and low, and also I tried to set the microsteps  0 2 4 8 ..128 256.  The TSTEP always be 0 1 2 3 and never a double-digit show to me.

The TSTEP is an important value for me to set threshold for coolStep, stealchop, spreadCycle, and as data sheet told us, its range should be 0 to 1048575 = (2^20)-1.

The value is really small.

do you have any idea for that?

Thanks!

**Comment by teemuatlut** [comment]
Not sure if you figured it out but you should try stepping inside an interrupt for more consistent step pulses.
